# Generated by Django 3.0.5 on 2020-04-30 03:38

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200, null=True)),
                ('category', jsonfield.fields.JSONField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=150)),
                ('image_urls', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('rating', models.TextField(blank=True)),
                ('rating_distribution', jsonfield.fields.JSONField(blank=True, max_length=150)),
                ('no_of_reviews', models.TextField(blank=True)),
                ('comments', jsonfield.fields.JSONField(blank=True)),
                ('commentator_name', jsonfield.fields.JSONField(blank=True)),
                ('commentator_rate', jsonfield.fields.JSONField(blank=True)),
                ('features', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
    ]
