# Generated by Django 3.0.5 on 2020-04-30 05:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200430_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_distribution',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
