# Generated by Django 3.0.5 on 2020-05-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200430_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_urls',
            field=models.TextField(blank=True, default=''),
        ),
    ]
