# Generated by Django 3.0.5 on 2020-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200507_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
