# Generated by Django 3.0.5 on 2020-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200507_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
