# Generated by Django 3.0.5 on 2020-05-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200507_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='commentss',
            new_name='comments',
        ),
    ]
