# Generated by Django 3.0.5 on 2020-05-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200507_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
    ]
