export const SEARCH_SUGGESTIONS = "SEARCH_SUGGESTIONS";
export const SEARCH_RESUALT = "SEARCH_RESUALT";
export const RESET_SEARCH_SUGGESTIONS = "RESET_SEARCH_SUGGESTIONS";

//  Actions for AutoComplete
export const FETCHING_AUTOCOMPLETE_STARTED = "FETCHING_AUTOCOMPLETE_STARTED";
export const FETCHING_AUTOCOMPLETE_SUCCEED = "FETCHING_AUTOCOMPLETE_SUCCEED";
export const FETCHING_AUTOCOMPLETE_FAILED = "FETCHING_AUTOCOMPLETE_FAILED";

//  Actions for Products Suggestions
export const FETCHING_RESULT_STARTED = "FETCHING_RESULT_STARTED";
export const FETCHING_RESULT_SUCCEED = "FETCHING_RESULT_SUCCEED";
export const FETCHING_RESULT_FAILED = "FETCHING_RESULT_FAILED";

//  Actions for Product Page
export const FETCHING_PRODUCT_STARTED = "FETCHING_PRODUCT_STARTED";
export const FETCHING_PRODUCT_SUCCEED = "FETCHING_PRODUCT_SUCCEED";
export const FETCHING_PRODUCT_FAILED = "FETCHING_PRODUCT_FAILED";
